### ISSUE TITLE
Compute the intensity of sequential genes after cell re-segmentation

### ISSUE THREAD

**Issue by Christina-hshi** [Vizgen/vizgen-postprocessing#15]
Hello,

Thanks for developing this powerful tool! I have been using it in re-segmenting the MERSCOPE data, and it performed very well so far in terms of improving the ratio of transcripts being assigned to cells.
However, I have sequential genes which are not in the merfish list. I am wondering whether you can re-calculate the density of sequential genes after cell re-segmentation. If you are busy in developing other features, I totally understand, and I wonder whether you can kindly offer some advice on how to do the calculation. 

Thanks,
Christina

**Comment by timwiggin** [comment]
Hi Christina,

Yes, VPT does allow estimation of the expression of genes in the sequential panel using the new segmentation. The `sum-signals` functionality quantifies the brightness of the mosaic images within each cell. It returns both the summed intensity of the raw image within the cell, and the summed intensity of a high-pass filtered version of the image. The high-pass filter is calibrated to enhance image features that are roughly the size of a smFISH spot.

In order to run sum-signals, you would use a command like this:
```
vpt --verbose --processes 8 sum-signals \
--input-images="/PATH_TO_INPUTS/region_0/images/mosaic_(?P<stain>GENE_NAME)_z(?P<z>[0-9]+).tif" \
--input-boundaries /PATH_TO_OUTPUTS/cellpose_micron_space.parquet \
--input-micron-to-mosaic /PATH_TO_INPUTS/region_0/images/micron_to_mosaic_pixel_transform.csv \
--output-csv /PATH_TO_OUTPUTS/sum_signals.csv
```
Link to documentation: https://vizgen.github.io/vizgen-postprocessing/command_line_interface/index.html#sum-signals

It’s important to note that the output of `sum-signals` is not in units of counts, it’s in units of intensity. Because of that difference in units, the `sum-signals` output may require some additional processing before you can integrate it with merfish transcript data. Because the details of that processing may vary depending on the expression level of the gene and the signal-to-noise ratio of the sequential gene output, we do not implement those data integration steps within VPT.

**Comment by Christina-hshi** [comment]
Hi Tim,

Sounds great! Thanks a lot!  
Do you have any advice on how to integrate the intensity info of the sequential genes into merfish transcript data? You mentioned that processing may vary depending on the expression level of the gene, and the signal-to-noise ratio. I wonder how we can use them to help with integration. Any advice is very appreciated!

**Comment by timwiggin** [comment]
As a first pass, I would recommend performing dimensionality reduction and clustering to create a projection of your data and using the `sum-signal` intensity as a label on the data. That will show if the sequential gene is expressed in the correct cell type / types and if the intensity is likely to be sufficient to distinguish positive vs. negative cells.

If plotting your data shows face validity, the next step would be to apply a model to your data, for example using a gaussian mixture model to assign your cells a probability of being positive vs negative for the gene of interest.

**Comment by Christina-hshi** [comment]
Thank you very much, Tim!  It helps a lot!

Best,
Christina
